export const BOOK_TICKET_REQUEST = 'BOOK_TICKET_REQUEST';
export const BOOK_TICKET_SUCCESS = 'BOOK_TICKET_SUCCESS';
export const BOOK_TICKET_FAIL = 'BOOK_TICKET_FAIL';
export const BOOK_TICKET_RESET = 'BOOK_TICKET_RESET';

export const GET_SHOWS_REQUEST = 'GET_SHOWS_REQUEST';
export const GET_SHOWS_SUCCESS = 'GET_SHOWS_SUCCESS';
export const GET_SHOWS_FAIL = 'GET_SHOWS_FAIL';